- name: Install nginx
  apt:
    name: nginx

- name: "Check if nginx is accessible."
  uri:
    url: http://127.0.0.1:80
    method: GET
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 15
  delay: 1