---
- hosts: prometheus
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_blackbox_exporter

- hosts: node_exporter
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - nginx

- hosts: node_exporter
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_node_exporter

- hosts: prometheus
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus

- hosts: alertmanager
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - alertmanager
  
- hosts: loki
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - loki

- hosts: grafana
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - grafana